# Copyright 2022 Huawei Technologies Co., Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ============================================================================

# model architecture
model_name: "nonlocal"

# The dataset sink mode.
dataset_sink_mode: False

# Context settings.
context:
    mode: 0 #0--Graph Mode; 1--Pynative Mode
    device_target: "GPU"

# model settings of every parts
model:
    type: nonlocal3d
    in_d: 32
    in_h: 224
    in_w: 224
    num_classes: 400
    keep_prob: 1.0

# learning rate for training process
learning_rate:
    lr_scheduler: "cosine_annealing"
    lr: 0.0003
    lr_epochs: [2, 4]
    lr_gamma: 0.1
    eta_min: 0.0
    t_max: 100
    max_epoch: 5
    warmup_epochs: 1

# optimizer for training process
optimizer:
    type: 'SGD'
    momentum: 0.9
    weight_decay: 0.0001

loss:
    type: SoftmaxCrossEntropyWithLogits
    sparse: True
    reduction: "mean"

train:
    pre_trained: False
    pretrained_model: ""
    ckpt_path: "./output/"
    epochs: 100
    save_checkpoint_epochs: 5
    save_checkpoint_steps: 1875
    keep_checkpoint_max: 10
    run_distribute: False

eval:
    pretrained_model: "/home/publicfile/checkpoint/nonlocal/nonlocal_mindspore.ckpt"

infer:
    pretrained_model: "/home/publicfile/checkpoint/nonlocal/nonlocal_mindspore.ckpt"
    batch_size: 1
    image_path: ""
    normalize: True
    output_dir: "./infer_output"

export:       # 模型导出为其他格式
    pretrained_model: "/home/publicfile/checkpoint/nonlocal/nonlocal_mindspore.ckpt"
    do_export: False
    include_dataset: False
    input_shape: [1, 3, 16, 256, 256]
    file_name: "nonlocal_mindspore"
    file_format: "MINDIR"

# Kinetic400 dataset config
data_loader:
    train:
        dataset:
              type: Kinetic400
              path: "/home/publicfile/kinetics-400"
              split: 'train'
              seq: 32
              seq_mode: 'interval'
              num_parallel_workers: 1
              shuffle: True
              batch_size: 6
              frame_interval: 6

        map:
            operations:
                - type: VideoShortEdgeResize
                  size: 256
                  interpolation: 'bicubic'
                - type: VideoRandomCrop
                  size: [224, 224]
                - type: VideoRandomHorizontalFlip
                  prob: 0.5
                - type: VideoRescale
                - type: VideoReOrder
                  order: [3, 0, 1, 2]
                - type: VideoNormalize
                  mean: [0.485, 0.456, 0.406]
                  std: [0.229, 0.224, 0.255]
            input_columns: ["video"]

    eval:
        dataset:
            type: Kinetic400
            path: "/home/publicfile/kinetics-400"
            split: 'val'
            seq: 32
            seq_mode: 'interval'
            num_parallel_workers: 1
            shuffle: False
            batch_size: 1
            frame_interval: 6
        map:
            operations:
                - type: VideoShortEdgeResize
                  size: 256
                  interpolation: 'bicubic'
                - type: VideoCenterCrop
                  size: [256, 256]
                - type: VideoRescale
                - type: VideoReOrder
                  order: [3, 0, 1, 2]
                - type: VideoNormalize
                  mean: [0.485, 0.456, 0.406]
                  std: [0.229, 0.224, 0.255]               
            input_columns: ["video"]
    group_size: 1
